config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  get '/search' => "recipes#search"

  resources :recipes

  resources :tags

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :step
  before_save :strip_amount

  private
  def strip_amount
    # Spaces are used later to parse amounts for calculation;
    # be sure no extra spaces are saved.
    self.amount = self.amount.strip
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :recipe_tags
  has_many :tags, through: :recipe_tags

  has_many :steps, dependent: :destroy
  has_many :ingredients, through: :steps

  accepts_nested_attributes_for :steps, reject_if: :reject_steps, allow_destroy: true

  def reject_steps(attributes)
    attributes['description'].blank?
  end

end

app/models/recipe_tag.rb
class RecipeTag < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :tag
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :recipe
  has_many :ingredients, dependent: :destroy

  accepts_nested_attributes_for :ingredients, reject_if: :reject_ingredients, allow_destroy: true

  def reject_ingredients(attributes)
    attributes['name'].blank? || attributes['amount'].blank? || attributes['unit'].blank?
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :recipe_tags
  has_many :recipes, through: :recipe_tags

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_step_index, only: [:new, :edit]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    3.times{ @recipe.steps.build }
    @recipe.steps.each do |s|
      s.ingredients.build
    end
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    query = params[:q]
    tags = params[:tag][:ids]

    # SELECT DISTINCT recipes.name
    #   FROM recipes
    #   INNER JOIN steps ON steps.recipe_id=recipes.id
    #   INNER JOIN ingredients ON ingredients.step_id=steps.id
    #   INNER JOIN recipe_tags ON recipe_tags.recipe_id=recipes.id
    #   INNER JOIN tags ON tags.id=recipe_tags.tag_id
    #   WHERE (tags.name="Entrees"  OR tags.name="Desserts") AND ingredients.name="cinnamon";

    @results = Recipe.joins(:tags, :ingredients).where(ingredients: {name: query}).uniq

    if !tags[0].blank?
      @results = @results.where(tags: {id: tags})
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :link, :notes, tag_ids: [], steps_attributes: [:id, :description, :_destroy, ingredients_attributes: [:id, :amount, :unit, :name, :_destroy]] )
    end

    def set_step_index
      @step_index = 0
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    # 3.times { @step.ingredients.build }
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all()
  end

  def new
    @tag = Tag.new()
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save()
      flash[:success] = "Tag was created."
      redirect_to tags_path
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      flash[:success] =  "Tag was updated."
      redirect_to tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy()
    flash[:success] = "Tag was deleted."
    redirect_to tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

  def set_tag
    @tag = Tag.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def consolidate_ingredients(recipes)
    # Takes an array of recipes (can contain just one recipe)
    # Consolidates multiple entries for ingredients with same name into one row

    # XXX For now assume just one recipe
    # XXX TODO:  Right now this assumes units across multiple entries are the same
    # (1 tbsp + 1/2 tbsp). Need to check for different units (1 tbsp + 1 cup).
    recipe = recipes[0]
    consolidated_ingredients = {}
    recipe.ingredients.each do |ing|
      if !consolidated_ingredients.key?(ing.name)
        # Add new entry
        consolidated_ingredients[ing.name] = {}
        consolidated_ingredients[ing.name]["amount"] = amount_to_rational(ing.amount)
        consolidated_ingredients[ing.name]["unit"] = ing.unit
      else
        # Add this amount to existing ingredient entry
        consolidated_ingredients[ing.name]["amount"] += amount_to_rational(ing.amount)
      end
    end

    consolidated_ingredients
  end

  private
  def amount_to_rational(amt)
    # Convert string amount from database into rational to use in calculations.
    # Leading/trailing whitespace has been stripped prior to saving.
    #
    # Amount may take any of these forms:
    #
    # "1"     - whole number, no spaces or slashes
    # "1/2"   - fraction, no spaces, one slash
    # "1 2/3" - mixed number, one or more digits in whole number, one space, one slash

    if !amt.include?(" ")
      if !amt.include?("/")
        # Whole number
        return Rational(amt.to_i)
      else
        # Fraction
        fraction_to_rational(amt)
      end
    else
      # Mixed number
      whole_num = amt.split(" ")[0].to_i
      fraction = fraction_to_rational(amt.split(" ")[1])
      return whole_num + fraction
    end
  end

  def fraction_to_rational(fraction)
    # Convert a fraction string (e.g. "1/2") to a rational
    numerator = fraction.split("/")[0]
    denominator = fraction.split("/")[1]
    return Rational(numerator, denominator)
  end

  def rational_to_mixed(rat)
    # Convert a rational to a mixed number for display (e.g. "3/2" -> "1 1/2")
    # Also returns display values for whole numbers and fractions
    int = rat.to_i
    if (int != rat.to_f) && (int > 0)
      # Mixed number
      fraction = rat - int
      "#{int} #{fraction}"
    else
      if rat.denominator == 1
        # Whole number; truncate denominator
        rat.to_i.to_s
      else
        # Fraction
        rat.to_s
      end
    end
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_navigation.html.erb
<li class="nav-item">
  <a class="nav-link active" href="/">Home</a>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Tags</a>
  <div class="dropdown-menu">
    <% @tags.each do |tag| %>
    <a class="dropdown-item" href="/">Home</a>
    <% end %>
  </div>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<div id="recipe-form">
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Link (optional)" %>
    <%= f.text_field :link, class:"form-control" %>
  </div>

  <div class="form-group" id="steps">
    <%= f.fields_for :steps do |steps_form| %>
      <div class="step-container">
        <h5>Step <%= steps_form.index + 1%></h5>
        <div class="row">
          <div class="ingredient-fields col-md-6">
              <% @ingredient_index = 0 %>
              <%= steps_form.fields_for :ingredients do |ingredients_form| %>
              <div class="row">
                <div class="col-md-3">
                  <%= ingredients_form.text_field :amount, placeholder: "1", class: "form-control" %>
                </div>
                <div class="col-md-3">
                  <%= ingredients_form.select :unit, options_for_select(['cups', 'tsp', 'tbsp', 'piece(s)', 'oz']), 
                    {}, {class: "form-control c-select"} %>
                </div>
                <div class="col-md-5">
                  <%= ingredients_form.text_field :name, placeholder: "ingredient", class: "form-control" %>
                </div>
                <div class="col-md-1">
                  <%= ingredients_form.check_box :_destroy, class: "form-control" %><small>x</small>
                </div>
              </div>
              <% @ingredient_index += 1 %>
              <% end %>
              <button class="add-ingredient" data-step-index="<%= steps_form.index %>" data-ing-index="<%= @ingredient_index %>">+</button>

          </div> <!-- End ingredient-fields -->
          <div class="form-group col-md-6">
            <%= steps_form.text_area :description, placeholder: "Directions...", class: "form-control" %>

            <%= steps_form.check_box :_destroy %>
            <%= steps_form.label "x" %>
          </div> <!-- End directions form-group -->
        </div> <!-- End row -->
      </div> <!-- End step-container -->

      <% @step_index += 1 %>
    <% end %>
  </div>
  <button class="add-step btn btn-secondary" data-step-index="<%= @step_index %>">Add a Step</button></li>

  <hr />
  <div class="form-group">
    <%= f.collection_check_boxes :tag_ids, Tag.all().order('name'), :id, :name do |cb| %>
      <% cb.label(class: "checkbox-inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save Recipe", class:"btn btn-primary" %>
  </div>
<% end %>
</div>

<br />
<%= javascript_include_tag 'add_fields.js' %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<div id="search">
  <%= form_tag("/search", method: "get") do %>
    <div class="row">
      <div class="form-group col-md-4">
        <%= label_tag(:q, "Search for ingredient:") %>
        <%= text_field_tag(:q) %>
      </div>
      <%= submit_tag("Search") %>
    </div>

    <div class="form-group" id="search-tags">
      <%= label_tag(:tag, "Filter by tag:") %>
      <%= collection_check_boxes(:tag, :ids, Tag.all, :id, :name) %>
    </div>

  <% end %>
</div>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.order("name").each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>
<br />
<%= link_to 'Show tags', tags_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/search.html.erb
<%= @results %>
<% @results.each do |result| %>
  <%= link_to result.name, recipe_path(result.id) %>
  <br />
<% end %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<% if @recipe.link.blank? %>
  <h1><%= @recipe.name %></h1>
<% else %>
  <h1><%= link_to @recipe.name, @recipe.link %></h1>
<% end %>
<div class="card">
<ul>
<% consolidate_ingredients([@recipe]).each do |ing| %>
  <li><%= rational_to_mixed(ing[1]['amount']) + " #{ing[1]['unit']} #{ing[0]}" %></li>
<% end %>
</ul>
</div>
<ul>
<% @recipe.steps.each_with_index do |step, index| %>
  <li>
  <h5>Step <%= index + 1 %></h5>
  <% step.ingredients.each do |ing| %>
    <%= ing.amount %>
    <%= ing.unit %>
    <%= ing.name %><br />
  <% end %>
  <br />
  <%= step.description %>
  </li>
  <hr />
<% end %>
</ul>
<h3>Notes:</h3>
<p><%= @recipe.notes %></p>
<h3>Tags:</h3>
<ul>
<% @recipe.tags.each do |tag| %>
  <li><%= tag.name %></li>
<% end %>
</ul>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.submit @tag.new_record? ? "Create Tag" : "Edit Tag" %>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit tag</h1>

<%= render "form" %>

app/views/tags/index.html.erb
<h1>Tags:</h1>
<%= link_to "New tag", new_tag_path %>

<ul>
<% @tags.each do |t| %>
  <li>
    <%= link_to t.name, tag_path(t) %>
    <small><%= link_to "edit", edit_tag_path(t) %></small>
    <small><%= link_to "delete", t, method: :delete, data: { confirm: "Are you sure you want to delete #{t.name}?"} %></small>
  </li>
<% end %>
</ul>

app/views/tags/new.html.erb
<h1>Add a tag</h1>

<%= render "form" %>

app/views/tags/show.html.erb
<% @tag.recipes.each do |recipe| %>
  <%= recipe.name %>
<% end %>